name: "Super Action Personalizada"
description: "Formatea código, saluda, y genera documentación automáticamente"
inputs:
  nombre:
    description: "ANDREA"
    required: true
  cena:
    description: "PIZZA BARBACOA"
    required: false
runs:
  using: "composite"
  steps:
    - run: bash ${{ github.action_path }}/saludo.sh "${{ inputs.nombre }}" "${{ inputs.cena }}"
      shell: bash
    - run: bash ${{ github.action_path }}/format.sh
      shell: bash
    - run: bash ${{ github.action_path }}/doc.sh
      shell: bash
    - run: bash ${{ github.action_path }}/update_readme_if_new_contributor.sh
      shell: bash
